- name: update packages
  become: true
  yum:
    name: "*"
    state: latest
- name: create utility  dir
  become: true
  file:
    path: /usr/local/share/etcd_autoscale
    state: directory
- name: drop etcd kubeconfig template on image
  become: true
  copy:
    src: etcd_kubeconfig.yaml.j2
    dest: /usr/local/share/etcd_autoscale/etcd_kubeconfig.yaml.j2

